CREATE DATABASE comicsDB CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE comicsDB;

DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS publishers;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS comics;
DROP TABLE IF EXISTS authors; 
DROP TABLE IF EXISTS comics_authors; 
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS comics_genres; 
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS comics_orders;
DROP TABLE IF EXISTS logins;

CREATE TABLE addresses (
address_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
street_num TINYINT UNSIGNED NOT NULL,
street VARCHAR(60) NOT NULL,
city VARCHAR(45) NOT NULL,
province VARCHAR(45) NOT NULL,
postal_code CHAR(6) NOT NULL,
PRIMARY KEY (address_id),
INDEX (postal_code)
) ENGINE = INNODB;

CREATE TABLE users (
user_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
address_id MEDIUMINT UNSIGNED NOT NULL,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR(45) NOT NULL,
email VARCHAR(60) NOT NULL,
pass CHAR(40) NOT NULL,
phone VARCHAR(12) NOT NULL,
gender ENUM('M','F') NOT NULL,
secret_question	VARCHAR(60) NOT NULL,
secret_answer VARCHAR(60) NOT NULL,
date_of_birth DATETIME NOT NULL,
registration_date DATETIME NOT NULL,
usertype ENUM('user','admin','staff') DEFAULT 'user',
PRIMARY KEY (user_id),
UNIQUE (email),
INDEX login (pass, email),
FOREIGN KEY (address_id) REFERENCES addresses (address_id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB;

CREATE TABLE publishers (
publisher_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR(45) NOT NULL,
PRIMARY KEY (publisher_id),
INDEX (last_name)
) ENGINE = INNODB;

CREATE TABLE categories (
category_id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
PRIMARY KEY (category_id),
INDEX (name)
) ENGINE = INNODB;

CREATE TABLE comics (
comic_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
publisher_id MEDIUMINT UNSIGNED NOT NULL,
category_id TINYINT UNSIGNED NOT NULL,
title VARCHAR(45) NOT NULL,
description VARCHAR(255) NOT NULL,
isbn VARCHAR(13) NOT NULL,
rating FLOAT(10,2) NOT NULL,
price DECIMAL(10,2) NOT NULL,
e_price DECIMAL(10,2) NOT NULL,
cover_img_path VARCHAR(60) NULL,
preview_img_path VARCHAR(60) NULL,
ecomic_file_path VARCHAR(60) NULL,
publishing_date DATETIME NOT NULL,
PRIMARY KEY (comic_id),
INDEX (title),
INDEX (price),
INDEX (rating),
FOREIGN KEY (publisher_id) REFERENCES publishers (publisher_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (category_id) REFERENCES categories (category_id) ON DELETE CASCADE ON UPDATE CASCADE 
) ENGINE = INNODB;

CREATE TABLE authors (
author_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
first_name VARCHAR(20) NOT NULL,
last_name VARCHAR(45) NOT NULL,
PRIMARY KEY (author_id),
INDEX (last_name)
) ENGINE = INNODB;

CREATE TABLE comics_authors (
comic_id MEDIUMINT UNSIGNED NOT NULL,
author_id MEDIUMINT UNSIGNED NOT NULL,
PRIMARY KEY (comic_id, author_id),
FOREIGN KEY (comic_id) REFERENCES comics (comic_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (author_id) REFERENCES authors (author_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;

CREATE TABLE genres (
genre_id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
PRIMARY KEY (genre_id),
INDEX (name)
) ENGINE = INNODB;

CREATE TABLE comics_genres (
comic_id MEDIUMINT UNSIGNED NOT NULL,
genre_id TINYINT UNSIGNED NOT NULL,
PRIMARY KEY (comic_id, genre_id),
FOREIGN KEY (comic_id) REFERENCES comics (comic_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (genre_id) REFERENCES genres (genre_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;

CREATE TABLE transactions (
transaction_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
user_id MEDIUMINT UNSIGNED NOT NULL,
amount DECIMAL(10,2) NOT NULL,
transaction_date DATETIME NOT NULL,
PRIMARY KEY (transaction_id),
FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB;

CREATE TABLE orders (
order_id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
user_id MEDIUMINT UNSIGNED NOT NULL,
quantity TINYINT UNSIGNED NOT NULL,
PRIMARY KEY (order_id),
INDEX(quantity),
FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB;

CREATE TABLE comics_orders (
comic_id MEDIUMINT UNSIGNED NOT NULL,
order_id MEDIUMINT UNSIGNED NOT NULL,
PRIMARY KEY (comic_id, order_id),
FOREIGN KEY (comic_id) REFERENCES comics (comic_id) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = INNODB;

CREATE TABLE logins (
user_id MEDIUMINT UNSIGNED NOT NULL,
login_date DATETIME NOT NULL,
PRIMARY KEY (user_id),
FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE = INNODB;